#hand tracking algorithm parameters
#authors:
#Mohammad Fattahi Sani - fattahi.m91@gmail.com

#============ Sensor list name


#/jason_stream_lables: ['S0','S1','S2','S3','S4','S5','S6','S7','S8','S9','S10','S11']
#/sensor_n_list : ['Sensor0',  'Sensor1',   'Sensor2',   'Sensor3',     'Sensor4',   'Sensor5',   'Sensor6', 'Sensor7',     'Sensor8', 'Sensor9', 'Sensor10', 'Sensor11']
#/sensor_f_list : ['Index_PIP','Index_DIP', 'Middle_DIP','Middle_PIP',  'Thumb_DIP','Thumb_MIP', 'Index_MIP', 'Middle_MIP', 'Elbow', 'Wrist', 'Thumb', 'Thumb_CMC']
#/sensor_rf_list: ['Index_MIP','Index_PIP', 'Middle_PIP', 'Middle_MIP', 'Thumb_MIP', 'Thumb_CMC', 'Wrist',    'Wrist',      'world', 'Elbow', 'Wrist', 'Thumb']

# IMPORTANT: The order should be from parent to child
#/jason_stream_lables: ['S8',          'S9',       'S7',             'S6',             'S10',          'S11',              'S5',           'S4',           'S3',             'S2',           'S0',         'S1']
/jason_stream_lables: ['S8',          'S9',       'S7',             'S6',             'S10',          'S11',              'S4',           'S5',           'S3',             'S2',           'S0',         'S1']

#/sensor_rf_raw_list:  ['Elbow_raw','Wrist_raw',  'Middle_MIP_raw',  'Index_MIP_raw',  'Thumb_raw',    'Thumb_CMC_raw',  'Thumb_MIP_raw','Thumb_DIP_raw','Middle_PIP_raw','IMiddle_DIP_raw','Index_PIP_raw', 'Index_DIP_raw']

#/sensor_rf_list:      ['world',     'Elbow',    'Wrist',            'Wrist',          'Wrist',        'Thumb',          'Thumb_CMC',    'Thumb_MIP',    'Middle_MIP',     'Middle_PIP',    'Index_MIP',  'Index_PIP']
#/sensor_f_list :      ['Elbow',     'Wrist',    'Middle_MIP',       'Index_MIP',      'Thumb',        'Thumb_CMC',      'Thumb_MIP',    'Thumb_DIP',    'Middle_PIP',     'Middle_DIP',    'Index_PIP',  'Index_DIP']
/sensor_rf_list:      ['world',     'Elbow',    'world',            'Middle_MIP',          'Wrist',        'Thumb',          'Thumb_CMC',    'Thumb_MIP',    'Middle_MIP',     'Middle_PIP',    'Index_MIP',  'Index_PIP']
/sensor_f_list :      ['Elbow',     'Wrist',    'Middle_MIP',       'Index_MIP',      'Thumb',        'Thumb_CMC',      'Thumb_MIP',    'Thumb_DIP',    'Middle_PIP',     'Middle_DIP',    'Index_PIP',  'Index_DIP']

#/jason_stream_lables: ['S8',          'S9',      'S4',       'S5',        'S6',      'S7',     'S10',          'S11',              'S5',           'S4',           'S3',             'S2',           'S0',         'S1']
#/sensor_rf_list:      ['world',     'world',   'Elbow',      'Elbow',   'thumb',     'Elbow',      'world',        'world',          'world',         'world',    'world',          'world',    'world',  'world']
#/sensor_f_list :      ['Elbow',     'Elbow2',    'thumb',    'thumb2',   'index',    'index2',   'Index_MIP',            'Thumb_CMC',      'Thumb_MIP',                  'Thumb_DIP',           'Middle_PIP',           'Middle_DIP',         'Index_PIP',  'Index_DIP']

#============ translations wrt world

/hft_tfw/Elbow: [0.5,0.0,0.0]
/hft_tfw/Elbow2: [0.5,0.0,0.0]
/hft_tfw/Elbow8: [0.5,0.0,0.0]

/hft_tfw/index: [0.5,0.0,0.0]
/hft_tfw/index2: [0.5,0.0,0.0]

/hft_tfw/thumb: [0.5,0.0,0.0]
/hft_tfw/thumb2: [0.5,0.0,0.0]

/hft_tfw/S4: [0.5,0.0,0.0]
/hft_tfw/Wrist: [0.7,0.0,0.0]
/hft_tfw/Wrist5: [0.7,0.0,0.0]
/hft_tfw/Wrist8: [0.7,0.0,0.0]
/hft_tfw/S5: [0.7,0.0,0.0]


/hft_tfw/Thumb: [0.0,-0.01,0.0]
/hft_tfw/Thumb_CMC: [0,0.01,0.0]
/hft_tfw/Thumb_MIP  : [0.5,0.0,0.0]
/hft_tfw/Thumb_DIP  : [0.5,0.0,0.0]

/hft_tfw/Middle_MIP  : [0.2,0.0,0.0]
/hft_tfw/Middle_PIP : [0.25,0.0,0.0]
/hft_tfw/Middle_DIP : [0.30,0.0,0.0]

/hft_tfw/Index_MIP   : [0.9,-0.02,0.0]
/hft_tfw/Index_PIP  : [1.1,-0.02,0.0]
/hft_tfw/Index_DIP  : [1.3,-0.02,0.0]

#============ translations wrt the previous frame

/hft_tf/Elbow: [0.0,0.0,0.0]              #wrt world
/hft_tf/Wrist: [0.0,0.1,0.0]            #wrt elbow


/hft_tf/Thumb: [0.0,-0.01,0.0]          #wrt wrist
/hft_tf/Thumb_CMC: [0,0.01,0.0]          #wrt thumb
/hft_tf/Thumb_MIP  : [0.5,0.0,0.0]        #wrt Thumb_CMC
/hft_tf/Thumb_DIP  : [0.5,0.0,0.0]        #wrt Thumb_MIP

/hft_tf/Middle_MIP: [0.1,0.0,0.0]         #wrt wrist
/hft_tf/Middle_PIP : [0.5,0.0,0.0]        #wrt Middle_MIP
/hft_tf/Middle_DIP : [0.5,0.0,0.0]        #wrt Middle_PIP

/hft_tf/Index_MIP:   [0.0,0.1,0.0]          #wrt wrist
/hft_tf/Index_PIP  : [0.0,0.1,0.0]        #wrt Index_MIP
/hft_tf/Index_DIP  : [0.0,0.1,0.0]        #wrt Index_PIP




